export const basicInfoListQuery = {
  sku: '',
  productGroupSku: '', //
  clientSku: '',
  unitName: '',
  productNameCn: '',
  developAdminName: '',
  buyerName: '',
  withBattery: '',
  withBatteryRemark: '',
  productBrandArr: [],
  productBrandType: '',
  brandName: '',
  warehouseShipping: '98',
  productType: '',
  starLevel: null,
  comeSource: '',
  ceAuth: false,
  ceOssUrl: '',
  developType: '',
  isCombSku: false,
  salePlatform: [],
  powerSocket: false,
  powerSocketSpec: '',
  checkMemo: '1',
  checkProportion: '15',
  productProperty: '1',
  productPropetyContent: '',
  productPropetyContent_gray: [],
  referenceUrlForeign: [''],
  referenceUrlInternal: [''],
  productClasses: [],
  recommClass: '',
  spec: '',
  length: 0,
  width: 0,
  height: 0,
  packLength: 0,
  packWidth: 0,
  packHeight: 0,
  packWeight: 0,
  cartonLength: 0,
  cartonWidth: 0,
  cartonHeight: 0,
  grossWeight: 0,
  netWeight: 0,
  cartonGrossWeight: 0,
  cartonNetEight: 0,
  cartonPcsNum: '',
}
export const commodityPriceListQuery = {
  productState: 6,
  batchNum: '',
  productStateRemark: '',
  supplyPrices: []
}
export const variationMGTListQuery = {
  productGroupSku: '',
  productGroupSkuName: '',
  productColor: '',
  productSize: ''
}
export const commodityRemarksListQuery = {
  isPersell: '',
  persellArrivalDate: '',
  persellSdate: '',
  pesellEdate: '',
  toDevelopMemo: '',
  receiptRemark: '',
  needToPackType: '1',
  upAttachmentUrl: '',
  toEditorMemo: '',
  toProcurementCheckMemo: '',
  imageMemo: '',
  toDeliveryPackNoteMemo: '',
  packingListDesc: '',
}
export const productPictureListQuery = {
  imageSource: '',
  imageSourceUrl: '',
  imageSize: '',
  baseInfoPic: []
}
export const commodityInfoListQuery = {
  productName: '',//
  pageTitle: '',
  mateKeyword: '',
  searchKeyword: '',
  mateDescription: '',
  productDescription: '',
  featureList: '',
  packingList: '',
}
export const customsInfoListQuery = {
  declarationName: '',
  declarationNameCn: '',
  declarationUrpose: '',
  declarationMaterial: '',
  importCountry: '',
  declarationCode: '',
  declarationReturnTaxrate: '',
  declarationPriceRate: '',
  declarationUnit: '',
  declarationElement: '',
  remark: '',
}
export const commodityReviewListQuery = {
  developStatus: 1,
  developRejectReasom: '',
  editStatus: 1,
  editRejectReason: '',
  imageStatus: 1,
  imageRejectReason: '',
  checkStatus: 1,
  checkRejectReason: ''
}
